<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
A   =  [[1 ,3, 4],
             [2 ,5, 7],
             [5, 9, 6]]
B   = [[1, 0, 0],
             [0 ,1, 0],
             [0, 0, 1]]
result = [[1, 3, 4],
             [2, 5, 7],
             [5, 9, 6]]             


def matrix_mul(A, B):
 for i in range (len(A)):
   for j in range (len(B)):
    result[i][j] = A[i][j] * B[i][j]
for r in result:
  print(r)


[1, 3, 4]
[2, 5, 7]
[5, 9, 6]


In [ ]:
A   = [[1 ,2],
      [3, 4]]
B   = [[1 ,2 ,3 ,4 ,5],
      [5, 6, 7, 8 ,9]]
result = [[11, 14, 17, 20, 23],
         [23 ,30, 37, 44, 51]]
def matrix_mul(A, B):
 for i in range (len(A)):
   for j in range (len(B)):
    result[i][j] = A[i][j] * B[i][j]
for r in result:
  print(r)


[11, 14, 17, 20, 23]
[23, 30, 37, 44, 51]


In [67]:
A   = [[1 ,2],
      [3, 4]]
B   = [[1 ,4],
      [5, 6],
      [7 ,8],
      [9 ,6]]
def matrix_mul(A, B):
 for i in range (len(A)):
   for j in range (len(B)):
    result[i][j] = A[i][j] * B[i][j]
 for r in result:
  print(r)

<h3> Q2: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
A='234'
K = '#'
res = re.sub(r'\d', K,A)
print(str(res))

###


In [ ]:
A ="a2b3c4"   

def result(data): 
  D=""
  for i in data:
    if (i.isnumeric()):
      D+="#"
  return D    
print (result(A))

###


In [ ]:
A= "abc"
def result(data):
    D=""
    for i in data:
      if (i.isnumeric()):
        D+=""
    return D
print(result(A))      
 

In [ ]:
A = "#2a$#b%c%561#"
def result(data): 
  D=""
  for i in data:
    if (i.isnumeric()):
      D+="#"
  return D    
print (result(A))
  

####


<h3> Q3: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 

```
# This is formatted as code
```

equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [65]:
def fun(x, a, b):
    if a == -1:
        v = int(x[b])/(b+1)
        for i in range(a+1,b+1):
            x[i] = v
    elif b == -1:
        v = int(x[a])/(len(x)-a)
        for i in range(a, len(x)):
            x[i] = v
    else:
        v = (int(x[a])+int(x[b]))/(b-a+1)
        for i in range(a,b+1):
            x[i] = v
    return x

def replace(text):
   
    x = text.replace(" ", " ").split(",")
    
    y = [i for i, v in enumerate(x) if v != '_']
    
    if y[0] != 0:
        y = [-1] + y
    
    if y[-1] != len(x)-1:
        y = y + [-1]    
    
    for (a, b) in zip(y[:-1], y[1:]): 
        fun(x,a,b)          
    return x

tests = [
    "_,_,_,24",
    "40,_,_,_,60",
    "80,_,_,_,_",
     "_,_,30,_,_,_,50,_,_"]

for i in tests:
  
  print(replace(i))
  
  



[6.0, 6.0, 6.0, 6.0]
[20.0, 20.0, 20.0, 20.0, 20.0]
[16.0, 16.0, 16.0, 16.0, 16.0]
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q4: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
s1 = input()
s2 = input()


split1 = s1.split(" ")
split2 = s2.split(" ")

set1 = set(split1)
set2 = set(split2)

print (len(set1&set2))

the first column F will contain only 5 uniques values
the second column S will contain only 3 uniques values
7


In [ ]:
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

def string_diff(s1, s2):
    diff = list(set(s1.split()) - set(s2.split()))
    diff2 = [c1 for c1 in s1.split() if c1 not in s2.split()]
    print(f"Words in S1 but not in S2 are : {diff2}")
    
string_diff(s1,s2)


Words in S1 but not in S2 are : ['first', 'F', '5']


In [ ]:
def string_diff(s2, s1):
    diff = list(set(s1.split()) - set(s2.split()))
    diff2 = [c1 for c1 in s1.split() if c1 not in s2.split()]
    print(f"Words in S2 but not in S1 are : {diff2}")
    
string_diff(s1,s2)


Words in S2 but not in S1 are : ['second', 'S', '3']
